name: Demo for Env variable
on: workflow_dispatch
env:
  APP_ENV: "dev"
jobs:
  env-demo:
    runs-on: ubuntu-latest
    env:
      APP_ENV: "test"
    steps: 
     - name: Connecting to Env
       env:
        APP_ENV: "prod"
        run: echo "App is connecting to $APP_ENV"
      
