name: MyFirstWorkflow
on: 
  push:
    branches: 
            -main
  workflow_dispatch:
  
  jobs:
    MyFirstJob:
      runs-on:ubuntu-latest
      steps:
        -run:echo"hello world"
        - name: Checkout
          uses: actions/checkout@v6.0.1
        - name: List files in repository
          run: |
            echo "The repository ${{ github.repository }} contains the following files"
            tree

      
    
