
name: MyFirstWorkflow
on: workflow_dispatch

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: |
          echo "Hello 1"
          echo "This is line 2"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Phase
        run: echo "This is test phase"

     

      
    
