
name: MyFirstWorkflow
on: workflow_dispatch

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: Multiple Jobs
        run: |
          echo "Inside Job1"
          echo "Inside line 2 of Job1"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Phase
        run: echo "This is test phase"

     

      
    
