name: Outputs Demo
on: push
jobs:
 build:
    runs-on: ubuntu-latest
    outputs: ${{steps.step1.outputs.version}}
    steps:
      - name: step one
        id: step1
        run: echo "version=0.1" >> $GITHUB_OUTPUT
 deploy:
   runs-on: ubuntu-latest
   needs: build
   steps: 
    - name: Step two
      run: echo "we are deploying the app with version ${{needs.build.outputs.version}}"
   
