name: Outputs Demo
on: push
jobs:
 job1:
    runs-on: ubuntu-latest
    steps:
      - name: step one
        id: step1
        run: echo "version=0.1" >> $GITHUB_OUTPUT
      - name: step two
        run: echo "The version is ${{steps.step1.outputs.version }}"
  
